title: nicanor.github.io
description: "Nicanor Perera"
author: "Nicanor Perera"
exclude: [README.md, LICENSE.md, Gemfile, Gemfile.lock]
gems: ["jekyll-paginate", "jekyll-feed"]

url: https://nicanor.github.io

permalink: /:categories/:year/:month/:title/
paginate_path: "/blog/page:num/"
paginate: 10

email: nicanorperera@gmail.com
github_username: nicanor
twitter_username: nicanorperera

source_url: "https://github.com/nicanor/nicanor.github.io/blob/master/"

license: "CC-by"
license_url: https://creativecommons.org/licenses/by/4.0/
